version: "3.9"

services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1911
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -uroot -p1911 --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: Ecommerce
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "8080:8080"

volumes:
  mysql_data:
