name: CI/CD Docker Hub

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Build e Testes
        run: ./mvnw clean verify -X

      - name: Listar testes que falharam
        if: failure()
        run: grep -H "Error" target/surefire-reports/*.txt || true

  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem
        run: ./mvnw clean package -DskipTests && docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest
