name: CI/CD Docker Hub

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_URL: jdbc:mysql://localhost:3306/testdb
      DB_USERNAME: test
      DB_PASSWORD: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Build e Testes
        run: ./mvnw clean verify -X

      - name: Listar testes que falharam
        if: failure()
        run: grep -H "Error" target/surefire-reports/*.txt || true

  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem
        run: ./mvnw clean package -DskipTests && docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest
