name: CI/CD Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: >-
          --privileged
          --health-cmd "docker info"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build e Testes
        run: ./mvnw clean verify

  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem (sem rodar testes de novo)
        run: ./mvnw clean package -DskipTests && docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest

